### ISSUE TITLE
Can irust repl evaluate code with release mode instead of debug mode?

### ISSUE THREAD

**Issue by baiguoname** [sigmaSd/IRust#113]
What can I do to execute the code with using release mode?

**Comment by baiguoname** [comment]
In my understanding, when I call `irust_repl.eval(some code),` there must be some executing process like `cargo run` on the `src\main.rs`. I mean whether I can call `cargo run --release` rather than `cargo run`.

**Comment by sigmaSd** [comment]
I just released a new version of irust_repl 0.21.0 that have this, you need to use `eval_with_configuration` and use `CompileMode::Release` https://github.com/sigmaSd/IRust/blob/master/crates/irust_repl/examples/re/main.rs#L27

fixed in https://github.com/sigmaSd/IRust/commit/7ce8b46eb18dc91d5bffd3ff9d0fe4ad87efeaec
