### ISSUE TITLE
Support nREPL protocol?

### ISSUE THREAD

**Issue by glyh** [sigmaSd/IRust#135]
Here's [nREPL's website](https://nrepl.org/nrepl/1.1/index.html). 

Basically it's a protocol that specify how evaluation should be done over network. This allow nice editor integration. E.g. for neovim we have [conjure](https://github.com/Olical/conjure), on emacs we have [cider](https://github.com/clojure-emacs/cider) (although cider is largely for clojure).

This will allow rust to have a conversational development experience like LISPs. I may hop in if PR is welcomed.

**Comment by sigmaSd** [comment]
Hello, here are my thoughts

- Seems like irust at one point was supported in conjure https://github.com/Olical/conjure/commit/d552de91126f9ae1a0b72ff4fdcf0f48e004240d it uses the local server feature , its just a simple server that allows rpc communication https://github.com/sigmaSd/IRust?tab=readme-ov-file#vim-plugin

- I also used to use conjure, but then I found https://github.com/Vigemus/iron.nvim which just works, but I understand its not 100% the same

- I'm not opposed to the nrepl protocol, but I prefer it to not be in the main binary, because it will need new dependencies (bencode for example) unless they're relly small
- other alternatives:
    - add this feature using scripts https://github.com/sigmaSd/IRust?tab=readme-ov-file#scripts , should be possible probably by adding a couple more scripts hooks
    - create a new program that uses https://github.com/sigmaSd/IRust/tree/master/crates/irust_repl#irust-repl directly , it have less feature, but its api is cleaner, and it should be straight forward to add this featre on top of it

**Comment by glyh** [comment]
This makes sense, I'll probably make a downstream project for it. Thank you!
