### ISSUE TITLE
Out: IRust: Are you missing a `;` ?

### ISSUE THREAD

**Issue by ulidtko** [sigmaSd/IRust#62]
Hi!

This rather simple code compiles just fine with `rustc`:
```rust
fn parse_troop_power(troops: &str) -> u32 {
    troops.split(' ')
          .map(|w| w.parse::<u32>().expect("input format"))
          .fold(0, |s, x| s + x)
}
```
But when *pasted* into IRust, gives weird error:

![Screenshot from 2019-12-04 00-28-55](https://user-images.githubusercontent.com/365338/70095306-16cb8f00-162d-11ea-9a3e-4cf1082e01a8.png)

Curiously, `:load` from a scratch-file works just fine, too. But it's the whole point of a REPL — to not have to use scratch files right?..

**Comment by ulidtko** [comment]
`irust --version` → 0.7.30, FWIW

**Comment by sigmaSd** [comment]
Hi welcome! As IRust suggest you have to add ';' at the end of the function definition
fn a() {}; instead of fn a() {}

**Comment by sigmaSd** [comment]
This issue reoccurs I guess I have to add a FAQ in the readme ^^

**Comment by smolck** [comment]
@sigmaSd The error IRust isn’t very helpful IMO because it doesn’t say anything about where the semicolon should go. Most people will probably expect (from other REPLs, like IPython) functions to not require semicolons at the end, and so won’t think to put a semicolon after the function definition. Is there any way we can remove that requirement? Or at least improve the error message?

**Comment by sigmaSd** [comment]
Hi @smolck ! I think you're right since by now I saw this issue come up a lot of times, maybe we can just special case functions structs and traits maybe?

Here is an initial test https://github.com/sigmaSd/IRust/commit/60e541ca704b8f4b9ef3756b03f67fd97a7bb9a3, would be great if you test it and report back, I just want to be sure of two things: 1- does it feel now like you expect 2- does it break other things

**Comment by sigmaSd** [comment]
I found no problem while testing it https://github.com/sigmaSd/IRust/commit/195cbec7f7579324ee750263221a257e39659df9, I think this should be resolved now

**Comment by ulidtko** [comment]
Yea, looks good to me. Closing!
