### ISSUE TITLE
Custom keybindings?

### ISSUE THREAD

**Issue by Aloxaf** [sigmaSd/IRust#82]
This project is cool!

Is there any plan to support custom keybindings?

**Comment by sigmaSd** [comment]
Hello,

Thanks for checking this project out!

Yes, Adding custom keybindings support is a good idea, I imagine it will be supported via scripting, but for that to happens, a couple of changes are needed:

1- The handling of events here https://github.com/sigmaSd/IRust/blob/master/crates/irust/src/irust/events.rs should return a command instead of executing the code directly, (inspired by nushell)

```rust
enum Command
HandleChar,
HandlerEnter,
HandlerCtrll
```

This will make it possible for a script to invoke them.

2- https://github.com/sigmaSd/IRust/blob/master/crates/irust/src/irust.rs#L128 here we can add something like,

```rust
if let Some(Command) = self.scriptmg.on_input_hook(ev) {
   self.engine.execute(command);
   return
}
```

Now script support can be added, this one might need to run as a daemon for performance since its called each keystroke, that sacrifices "hot reloading" but we'll see how this goes.

**Comment by Aloxaf** [comment]
Well, that's pretty good!

**Comment by sigmaSd** [comment]
IRust version 1.9.0 now supports input event hook, feel free to check out the vim mode example https://github.com/sigmaSd/IRust/blob/master/scripts_examples/script2/input_event/src/main.rs

**Comment by Aloxaf** [comment]
Thanks for your quick work!

I am trying to write an Emacs mode, and come across these problems:

1. Some command name not very intuitive. For example, `Eval` may be a better name compared to `HandleCtrlE`?
2. `GlobalVariables` is lack of something like current suggestion state (to use <kbd>enter</kbd> both for accept suggestions and accept-line) and current session id (to avoid state conflict between different irust session).

**Comment by sigmaSd** [comment]
1- The names are just placeholder for now, they definitly need to change and be commented now they are part of the public api

2- I can add is_sugesstion_active to GlobalVariables and a AcceptSugesstion command to the api

For the session_id, currently all irust instances share the same underlying repl, for this to work some changes are needed before to irust_repl crate, do you think this is a good feature? Im not sure if there is an important  benefit to making sessions unique


Btw thanks for making the emacs extention, this showcases the api shortcommings, feel free to open a pr with it!

**Comment by sigmaSd** [comment]
Also I want to add that Im still experimenting with scripting, my next idea is ( for scriptv3) 

- Remove the binary names constraint
- At startup make IRust search script directory for any executable and run it, it should respond with what hooks its interested in and what is its execution type (oneshot/daemon) 
- save its path and desired hooks in a map if its a oneshot / Run it if its a daemon and save the child process and desired hooks in another map 
- Now each time a hook is triggered , look for a script that asked for it and activate it

**Comment by Aloxaf** [comment]
> For the session_id, currently all irust instances share the same underlying repl, for this to work some changes are needed before to irust_repl crate, do you think this is a good feature? Im not sure if there is an important benefit to making sessions unique

I just mean to have an id (PID is enough) so that I can create a file like `/tmp/input_event_ID/mode`. Without this, if an instance enter normal mode, other instances will also enter normal mode.
Or let the script can run in daemon mode will also be OK.

The scriptv3 seems will solve this problem and improve performance, that's great!

**Comment by sigmaSd** [comment]
For now I added  `pid` and `is_racer_suggestion_active` to Globals and `AcceptSuggestion` to Commands https://github.com/sigmaSd/IRust/commit/14c771c64c1ff06c2bd71b7a6feb1cd94ee5fc06

**Comment by sigmaSd** [comment]
I added script v3 and a bunch of new commands, here is the new vim script https://github.com/sigmaSd/IRust/blob/master/scripts_examples/script3/irust_vim/src/main.rs

**Comment by Aloxaf** [comment]
Nice!

I am implementing an Emacs keybinding based on script3 now: https://github.com/Aloxaf/IRust/blob/irust_emacs/scripts_examples/script3/irust_emacs/src/main.rs

**Comment by sigmaSd** [comment]
Nice, Your emacs script is way more organized!

If you find that some important features/commands are missing, feel free to list them here so I can adress it when I can

**Comment by sigmaSd** [comment]
I added a Pr for your emacs script https://github.com/Aloxaf/IRust/pull/1

I think I want to see if I can rework the script system so everything is guaranteed by the type system, since currently bug like this are easy to make and their manifestation are actually random.

**Comment by Aloxaf** [comment]
> I added a Pr for your emacs script [Aloxaf#1](https://github.com/Aloxaf/IRust/pull/1)

Thanks!

> I think I want to see if I can rework the script system so everything is guaranteed by the type system, since currently bug like this are easy to make and their manifestation are actually random.

That would be nice.

**Comment by sigmaSd** [comment]
I added a section about keybindings here https://sigmasd.github.io/irust_book/custom-keybindings/

I tried adding more compile time guarantees but it was not straightforward, and made the scripting system weaker.

I think I'll just keep it like this for now and improve it Iteratively.

I'll close this issue for now since keybindings are possible, feel free to reopen it if something is missing or open a different issue.
