### ISSUE TITLE
[Feature Request]: Ability to load custom `Cargo.toml`

### ISSUE THREAD

**Issue by AZMCode** [sigmaSd/IRust#86]
To start with, implementation of this feature could solve #85 and possible other future errors.

It would be useful to test code for a crate to load the preexisting `Cargo.toml` file, possibly with various settings that could affect crate loading, such as the current crate being a `proc_macro` crate as described in the mentioned Issue, the features which a crate is loaded with, the `cargo-features` in use, etc. It would also make the process of testing code for a crate faster, since we would not have to `:add` each package separately, or load a preexisting file.

**Comment by sigmaSd** [comment]
I can allow that, or just editing the toml file, with `:edit_cargo_toml` command, but I feel this should be an internal thing since messing up the toml file can easily mess the repl

I prefer to expose any feature needed via commands, so feel free to open issues with the feature you're missing

proc_macro is a good example since even manually messing with the toml file wont make it work

Btw `:add` can accept multiple packages: `:add rand serde`
