### ISSUE TITLE
Use `rust-analyser` instead of `racer` for autocompletion

### ISSUE THREAD

**Issue by Techcable** [sigmaSd/IRust#92]
Hi! This looks like a cool project.

Have you considered using `rust-anlayser` for autocompletion instead of `racer`? In my experience, rust-anlayser has much better autocompletion than either racer or RLS.

The racer project isn't really actively maintained, and users are more likely to have rust-analyser installed than either RLS or racer.

As of [RFC 2912](https://github.com/rust-lang/rfcs/blob/master/text/2912-rust-analyzer.md), `rust-analyser` is semi-official and there are plans to integrate it into `dustup`.

The best solution would probably be to use a language-server client instead of depending on it directly. The [lsp-types][(https://lib.rs/crates/lsp-types](https://docs.rs/lsp-types/) crate shouldn't make this too hard 😉 

Also I believe [evcxr](https://github.com/google/evcxr) depends on the rust-analyser internal API (and requires compiling it directly).

**Comment by sigmaSd** [comment]
Hello, thanks for checking out the project

It is of course on my radar, I don't believe I will have time for it though

Racer have some advantages worth mentioning:
- it requires no additional dependencies from irust side
- ra requires at least more then 100mb the first time it spawned then it will keep growing 

I believe that ra support needs to be added sooner or later, the only immediate problems is the work needed and that the benefit want be obvious initially to the user since irust would also need some changes to make a really good use of ra ( like maybe nicer auto completion ux, goto definition support, etc)

**Comment by AddictArts** [comment]
+1 racer is no longer in development as I'm sure you know. Also, it does not build anymore and using a nightly rustc is not a good experience.

**Comment by sigmaSd** [comment]
If someone wants to take this I think https://github.com/helix-editor/helix/tree/master/helix-lsp is the easiest implementation to copy.

**Comment by sigmaSd** [comment]
I'm happy to say, that I have a working prototype with ra, if some one want to test or give some technical feedback the code is here https://github.com/sigmaSd/IRust/tree/ra

**Comment by sigmaSd** [comment]
PR https://github.com/sigmaSd/IRust/pull/117

**Comment by AddictArts** [comment]
Thank you. I will be looking at it as soon as I can, but Rust right now is personal time, so harder to get in front of me.

**Comment by AddictArts** [comment]
This doesn't seem to work on Windows, helix does fyi. How can I tell rust-analyzer is enabled?
